services:
  db:
    image: mariadb:12
    restart: always
    environment:
      - MYSQL_DATABASE=fa-db
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./db:/var/lib/mysql
    # ports:
    #   - "3310:3306"
    networks:
      - internal
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: omarmokhtar99/fa
    restart: always
    depends_on:
      db:
        condition: service_healthy
    volumes:
      # - ./FA:/var/www/html
      # Uncomment the lines below to use persistent storage for specific directories/files
      - ./FA/tmp:/var/www/html/tmp
      - ./FA/modules:/var/www/html/modules
      - ./FA/config.php:/var/www/html/config.php
      - ./FA/config_db.php:/var/www/html/config_db.php
      - ./FA/company:/var/www/html/company
    networks:
      - npm
      - internal

networks:
  npm:
    external: true
  internal:
    driver: bridge